import {useEffect,useState} from 'react';
import {api,setCsrf} from './api';
import {User,Release,Criterion,Blocker,Approval,Risk,Audit} from './types';
import {CriteriaPanel} from './CriteriaPanel';
import {BlockersPanel} from './BlockersPanel';
import {ApprovalsPanel} from './ApprovalsPanel';
import {InsightsPanel} from './InsightsPanel';
const transitions:Record<string,string[]>={draft:['in_review','cancelled'],in_review:['approved','draft','cancelled'],approved:['released','in_review','cancelled'],released:[],cancelled:['draft']};
export default function App(){
 const [user,setUser]=useState<User|null>(null);const [mode,setMode]=useState('oidc');const [loaded,setLoaded]=useState(false);const [releases,setReleases]=useState<Release[]>([]);const [total,setTotal]=useState(0);const [page,setPage]=useState(1);const [selected,setSelected]=useState<Release|null>(null);const [criteria,setCriteria]=useState<Criterion[]>([]);const [blockers,setBlockers]=useState<Blocker[]>([]);const [approvals,setApprovals]=useState<Approval[]>([]);const [risk,setRisk]=useState<Risk|null>(null);const [audit,setAudit]=useState<Audit[]>([]);const [tab,setTab]=useState('criteria');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [name,setName]=useState('');const [version,setVersion]=useState('1.0.0');const [description,setDescription]=useState('');
 const operator=!!user?.roles.some(r=>['reviewer','admin'].includes(r));const admin=!!user?.roles.includes('admin');const editable=operator&&!!selected&&['draft','in_review'].includes(selected.status);
 useEffect(()=>{let active=true;Promise.all([api<{mode:string}>('/api/auth/mode'),api<User>('/api/auth/me').catch(()=>null)]).then(([m,u])=>{if(active){setMode(m.mode);setUser(u);if(u)setCsrf(u.csrf_token);setLoaded(true);}}).catch(e=>{setError(e.message);setLoaded(true);});return()=>{active=false;};},[]);
 async function list(p=page){const data=await api<{items:Release[];total:number}>('/api/releases/?page='+p+'&per_page=20');setReleases(data.items);setTotal(data.total);}
 useEffect(()=>{if(user)list().catch(e=>setError(e.message));},[user,page]);
 async function login(identity:string){setError('');try{const u=await api<User>('/api/auth/demo?identity='+identity,'POST');setCsrf(u.csrf_token);setUser(u);}catch(e){setError((e as Error).message);}}
 async function logout(){try{await api('/api/auth/logout','POST');setUser(null);setSelected(null);setCsrf('');setReleases([]);}catch(e){setError((e as Error).message);}}
 async function open(id:string){setBusy(true);setError('');try{const [r,c,b,a,k,h]=await Promise.all([api<Release>('/api/releases/'+id),api<Criterion[]>('/api/criteria/release/'+id),api<Blocker[]>('/api/blockers/release/'+id),api<Approval[]>('/api/approvals/release/'+id),api<Risk>('/api/releases/'+id+'/risk-assessment'),api<{items:Audit[]}>('/api/audit/release/'+id)]);setSelected(r);setCriteria(c);setBlockers(b);setApprovals(a);setRisk(k);setAudit(h.items);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function refresh(){if(selected)void open(selected.id);void list().catch(e=>setError(e.message));}
 async function create(){setBusy(true);setError('');try{const r=await api<Release>('/api/releases/','POST',{name,version,description});setName('');setDescription('');await list();await open(r.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function transition(status:string){if(!selected)return;setBusy(true);setError('');try{await api('/api/releases/'+selected.id+'/transition','POST',{status});await open(selected.id);await list();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(){if(!selected||!window.confirm('Delete this unreleased release and its evidence? The audit remains.'))return;setBusy(true);try{await api('/api/releases/'+selected.id,'DELETE');setSelected(null);await list();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!loaded)return <main><p role="status">Connecting…</p></main>;
 if(!user)return <main className="login"><div className="eyebrow">RYAN VO · AI / DEVOPS</div><h1>Release Readiness Board</h1><p>Move from scattered checklists to evidence-backed release decisions, independent approvals and an auditable history.</p><a className="button" href="/api/auth/login">Sign in with SSO</a>{mode==='demo'&&<section className="panel"><h2>Local demonstration</h2><p>Use analyst to create a release, reviewer for an independent decision, and admin for final approval.</p><div className="actions">{['analyst','reviewer','admin'].map(x=><button key={x} onClick={()=>login(x)}>Demo {x}</button>)}</div></section>}{error&&<p role="alert" className="error">{error}</p>}</main>;
 return <><header><div><div className="eyebrow">RYAN VO · AI / DEVOPS</div><h1>Release Readiness Board</h1></div><div className="identity"><span>{user.username} · {user.roles.join(', ')}</span><button className="secondary" onClick={logout}>Sign out</button></div></header><main>{error&&<p role="alert" className="error">{error}</p>}{busy&&<p role="status">Loading current release state…</p>}
 {!selected?<><section className="panel"><div className="section-head"><h2>Releases ({total})</h2><button className="secondary" onClick={()=>list().catch(e=>setError(e.message))}>Refresh list</button></div>{releases.map(r=><article key={r.id}><div className="section-head"><div><h3>{r.name} · {r.version}</h3><p>{r.status} · evidence revision {r.revision} · risk index {r.risk_score}</p></div><button disabled={busy} onClick={()=>open(r.id)}>Open release</button></div></article>)}{!releases.length&&<p>No releases yet. Create a draft to start collecting evidence.</p>}<div className="actions"><button className="secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page}</span><button className="secondary" disabled={page*20>=total} onClick={()=>setPage(p=>p+1)}>Next</button></div></section>{operator&&<section className="panel"><h2>Create release</h2><div className="form-grid"><label>Release name<input value={name} maxLength={200} onChange={e=>setName(e.target.value)}/></label><label>Version<input value={version} maxLength={50} onChange={e=>setVersion(e.target.value)}/></label></div><label>Description<textarea value={description} maxLength={2000} onChange={e=>setDescription(e.target.value)}/></label><button disabled={busy||!name.trim()||!version.trim()} onClick={create}>Create draft</button></section>}</>:<><section className="panel"><div className="section-head"><div><h2>{selected.name} · {selected.version}</h2><p>{selected.status} · evidence revision {selected.revision} · creator {selected.created_by}</p></div><button className="secondary" onClick={()=>setSelected(null)}>All releases</button></div><p>{selected.description}</p><div className="metrics"><div><strong>{selected.criteria_summary.required_passed}/{selected.criteria_summary.required_total}</strong> required criteria passed</div><div><strong>{selected.blocker_summary.open}</strong> open blockers</div><div><strong>{selected.risk_score}</strong> heuristic risk index</div></div><div className="actions">{operator&&transitions[selected.status].filter(s=>s!=='approved'||admin).map(s=><button key={s} disabled={busy} onClick={()=>transition(s)}>Move to {s.replace('_',' ')}</button>)}{admin&&selected.status!=='released'&&<button className="danger" disabled={busy} onClick={remove}>Delete release</button>}</div>{!editable&&<p className="notice">Evidence is read-only in this state. Approved releases must return to review before changes; released records are frozen.</p>}</section>
 <nav aria-label="Release sections">{['criteria','blockers','approvals','insights'].map(t=><button key={t} className={tab===t?'active':'secondary'} onClick={()=>setTab(t)}>{t.charAt(0).toUpperCase()+t.slice(1)}</button>)}</nav>
 {tab==='criteria'&&<CriteriaPanel rid={selected.id} items={criteria} editable={editable&&!busy} refresh={refresh}/>}{tab==='blockers'&&<BlockersPanel rid={selected.id} items={blockers} editable={editable&&!busy} refresh={refresh}/>}{tab==='approvals'&&<ApprovalsPanel release={selected} items={approvals} user={user} refresh={refresh}/>}{tab==='insights'&&<InsightsPanel rid={selected.id} risk={risk} audit={audit} editable={operator} />}</>}
 </main><footer>Ryan Vo · <a href="mailto:ryandtvo@gmail.com">ryandtvo@gmail.com</a> · Human decisions, traceable evidence.</footer></>;
}
