import {useState} from 'react';
import {Approval,Release,User} from './types';
import {api} from './api';
export function ApprovalsPanel({release,items,user,refresh}:{release:Release;items:Approval[];user:User;refresh:()=>void}){
 const [decision,setDecision]=useState('approved');const [conditions,setConditions]=useState('');const [comment,setComment]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const eligible=user.subject!==release.created_by&&release.status==='in_review'&&user.roles.some(r=>['admin','reviewer'].includes(r));
 async function submit(){setBusy(true);setError('');try{await api('/api/approvals/','POST',{release_id:release.id,decision,conditions,comment});setComment('');refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function revoke(id:string){setBusy(true);setError('');try{await api('/api/approvals/'+id,'DELETE');refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const latest=new Map<string,string>();for(const a of items){if(a.release_revision===release.revision&&!latest.has(a.approver))latest.set(a.approver,a.id);}
 return <section className="panel"><h2>Independent approval</h2><p>Decisions apply only to evidence revision {release.revision}. The latest decision per reviewer counts; a current rejection or condition prevents approval. The release creator cannot approve their own work.</p>{eligible?<><label>Decision<select value={decision} onChange={e=>setDecision(e.target.value)}>{['approved','rejected','conditional'].map(s=><option key={s}>{s}</option>)}</select></label><label>Approval comment<textarea value={comment} maxLength={2000} onChange={e=>setComment(e.target.value)}/></label>{decision==='conditional'&&<label>Conditions<textarea value={conditions} maxLength={2000} onChange={e=>setConditions(e.target.value)}/></label>}<button disabled={busy||(decision==='conditional'&&!conditions.trim())} onClick={submit}>Record decision</button></>:<p className="notice">An independent reviewer can record a decision while the release is in review. In local demo mode, sign out and use a different demo identity.</p>}{error&&<p role="alert" className="error">{error}</p>}
 {items.map(a=><article key={a.id}><strong>{a.approver}: {a.decision}</strong><p>Revision {a.release_revision} · {latest.get(a.approver)===a.id?'Current decision':'Historical / superseded'} · {a.created_at}</p><p>{a.comment}</p>{a.conditions&&<p>Conditions: {a.conditions}</p>}{user.roles.includes('admin')&&release.status!=='released'&&<button className="danger" disabled={busy} onClick={()=>revoke(a.id)}>Revoke decision</button>}</article>)}{!items.length&&<p>No approval decisions recorded.</p>}</section>;
}
