import {useState} from 'react';
import {Blocker} from './types';
import {api} from './api';
export function BlockersPanel({rid,items,editable,refresh}:{rid:string;items:Blocker[];editable:boolean;refresh:()=>void}){
 const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [severity,setSeverity]=useState('medium');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function add(){setBusy(true);setError('');try{await api('/api/blockers/','POST',{release_id:rid,title,description,severity});setTitle('');setDescription('');refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel"><h2>Blockers and risk acceptance</h2><p>Every blocker must be resolved or explicitly accepted before approval. Classification uses a transparent keyword heuristic and may need correction.</p>{editable&&<><div className="form-grid"><label>Blocker title<input value={title} maxLength={300} onChange={e=>setTitle(e.target.value)}/></label><label>Severity<select value={severity} onChange={e=>setSeverity(e.target.value)}>{['critical','high','medium','low'].map(s=><option key={s}>{s}</option>)}</select></label></div><label>Blocker description<textarea value={description} maxLength={5000} onChange={e=>setDescription(e.target.value)}/></label><button disabled={busy||!title.trim()||!description.trim()} onClick={add}>Add blocker</button></>}{error&&<p role="alert" className="error">{error}</p>}{items.map(item=><BlockerEditor key={item.id+item.status} item={item} editable={editable} refresh={refresh}/>)}{!items.length&&<p>No recorded blockers. This is not evidence that no risk exists.</p>}</section>;
}
function BlockerEditor({item,editable,refresh}:{item:Blocker;editable:boolean;refresh:()=>void}){
 const [resolution,setResolution]=useState(item.resolution);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function act(status:string){setBusy(true);setError('');try{await api('/api/blockers/'+item.id,'PUT',{status,resolution});refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <article><h3>{item.title} <span className="badge">{item.severity} · {item.status}</span></h3><p>{item.description}</p><p className="muted">Category: {item.category}</p><label>Resolution for {item.title}<textarea value={resolution} maxLength={2000} disabled={!editable} onChange={e=>setResolution(e.target.value)}/></label>{editable&&<div className="actions"><button disabled={busy||resolution.trim().length<5} onClick={()=>act('resolved')}>Resolve blocker</button><button className="secondary" disabled={busy||resolution.trim().length<5} onClick={()=>act('accepted')}>Accept risk with rationale</button><button className="secondary" disabled={busy} onClick={()=>act('open')}>Reopen blocker</button></div>}{error&&<p role="alert" className="error">{error}</p>}</article>;
}
