import {useState} from 'react';
import {Criterion} from './types';
import {api} from './api';
export function CriteriaPanel({rid,items,editable,refresh}:{rid:string;items:Criterion[];editable:boolean;refresh:()=>void}){
 const [name,setName]=useState('');const [category,setCategory]=useState('testing');const [required,setRequired]=useState(true);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function add(){setBusy(true);setError('');try{await api('/api/criteria/','POST',{release_id:rid,name,category,required});setName('');refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel"><h2>Release criteria</h2><p>Required criteria need recorded evidence and a passing review. Changing evidence invalidates prior approvals and resets reviewed criteria to pending.</p>{editable&&<div className="form-grid"><label>Criterion name<input value={name} maxLength={200} onChange={e=>setName(e.target.value)}/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{['testing','security','performance','documentation','compliance','infrastructure'].map(s=><option key={s}>{s}</option>)}</select></label><label className="check"><input type="checkbox" checked={required} onChange={e=>setRequired(e.target.checked)}/>Required</label><button disabled={!name.trim()||busy} onClick={add}>Add criterion</button></div>}{error&&<p role="alert" className="error">{error}</p>}
 {items.map(item=><CriterionEditor key={item.id+item.status+item.evidence} item={item} editable={editable} refresh={refresh}/>)}{!items.length&&<p>No criteria yet. Add at least one required criterion before requesting approval.</p>}</section>;
}
export function CriterionEditor({item,editable,refresh}:{item:Criterion;editable:boolean;refresh:()=>void}){
 const [evidence,setEvidence]=useState(item.evidence);const [owner,setOwner]=useState(item.assigned_to);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function act(action:string){setBusy(true);setError('');try{if(action==='save')await api('/api/criteria/'+item.id,'PUT',{evidence,assigned_to:owner});else await api('/api/criteria/'+item.id+'/review','POST',{status:action});refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <article><h3>{item.name} <span className="badge">{item.required?'Required':'Optional'} · {item.status}</span></h3><p>{item.category} · Reviewed by {item.reviewed_by||'nobody yet'}</p><label>Evidence for {item.name}<textarea value={evidence} maxLength={5000} disabled={!editable} onChange={e=>setEvidence(e.target.value)}/></label><label>Owner for {item.name}<input value={owner} maxLength={100} disabled={!editable} onChange={e=>setOwner(e.target.value)}/></label>{editable&&<div className="actions"><button disabled={busy} onClick={()=>act('save')}>Save evidence</button><button disabled={busy||!item.evidence.trim()} onClick={()=>act('passed')}>Pass review</button><button className="secondary" disabled={busy} onClick={()=>act('failed')}>Fail review</button><button className="secondary" disabled={busy||item.required} onClick={()=>act('waived')}>Waive optional criterion</button></div>}{error&&<p role="alert" className="error">{error}</p>}</article>;
}
