import {useState} from 'react';
import {Risk,Audit} from './types';
import {api,download} from './api';
export function InsightsPanel({rid,risk,audit,editable}:{rid:string;risk:Risk|null;audit:Audit[];editable:boolean}){
 const [error,setError]=useState('');const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [advice,setAdvice]=useState<unknown>(null);const [diagnostics,setDiagnostics]=useState<unknown>(null);
 async function adviceRequest(){setBusy(true);setError('');try{setAdvice(await api('/api/llm/analyze/'+rid,'POST',{consent:true}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function exportFile(format:string){try{await download(`/api/releases/${rid}/export/${format}`,`release-${rid}.${format==='markdown'?'md':format}`);}catch(e){setError((e as Error).message);}}
 async function evaluate(){try{setDiagnostics(await api('/api/evaluation'));}catch(e){setError((e as Error).message);}}
 return <section className="panel"><h2>Readiness insights and release notes</h2>{risk&&<><div className="metrics"><div><strong>{risk.risk_score}</strong> heuristic risk index / 100</div><div><strong>{risk.risk_level}</strong> heuristic category</div><div><strong>{risk.ready_for_release?'Met':'Not met'}</strong> release evidence gate</div></div><p>The index uses fixed weights and keyword features. It is not a trained model, a calibrated failure probability, or permission to release. The evidence gate is enforced independently.</p><ul>{risk.risk_factors.map(x=><li key={x}>{x}</li>)}</ul><h3>Suggested next steps</h3><ul>{risk.recommendations.map(x=><li key={x}>{x}</li>)}</ul><details><summary>Scoring features and historical patterns</summary><pre>{JSON.stringify({features:risk.features,patterns:risk.patterns},null,2)}</pre></details></>}
 <div className="actions">{['json','markdown','csv'].map(f=><button key={f} className="secondary" onClick={()=>exportFile(f)}>Export {f.toUpperCase()}</button>)}</div><h3>AI/ML evaluation</h3><p>Run a deterministic diagnostic corpus covering risk monotonicity, clean/blocked releases and keyword classification. It is a regression check, not general accuracy evidence.</p><button className="secondary" onClick={evaluate}>Run diagnostics</button>{diagnostics!==null&&<pre>{JSON.stringify(diagnostics,null,2)}</pre>}
 <h3>Optional model advice</h3><p>Send summary counts and release metadata to the configured model only with explicit consent. Suggestions are untrusted and never change approval status.</p><label className="check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I consent to sending release metadata to the configured provider.</label><button disabled={!consent||!editable||busy} onClick={adviceRequest}>{busy?'Requesting…':'Request advice'}</button>{advice!==null&&<pre>{JSON.stringify(advice,null,2)}</pre>}{error&&<p role="alert" className="error">{error}</p>}
 <h3>Audit history</h3><p>Latest 50 events for this release, newest first.</p>{audit.map(a=><details key={a.id}><summary>{a.timestamp} · {a.entity_type}: {a.action}</summary><p>{a.user_id} · {a.details}</p><pre>{JSON.stringify({before:a.old_value,after:a.new_value},null,2)}</pre></details>)}</section>;
}
